### ISSUE TITLE
Sensor Data not refreshing

### ISSUE THREAD

**Issue by Hans1205** [fdebrus/hayward-ha#7]
Hello fdebrus,

First of all, a huge compliment on the integration and the speed with which you respond to requests. That's really great. I also know that you are on vacation and I don't want to disturb you on vacation. 

So maybe for after your vacation: 
After the numerous adjustments of the last few days, I noticed that the sensor data for the integration is no longer being updated. I updated to version 0.0.7 yesterday and all sensor data (e.g. pH, RX, temperature) was last updated 16 hours ago. That can't be intentional, can it?

However, the controls are still working! That's really good!

![image](https://github.com/fdebrus/hayward-ha/assets/155920388/c5ab532f-e0dd-4326-936e-0890d1e518c0)

**Comment by fdebrus** [comment]
remove the integration, go to HACS, "update information" then "re-download", restart HA, re-install the integration.
I do not have issue with 0.0.7

![image](https://github.com/fdebrus/hayward-ha/assets/33791533/63b9662e-025a-4298-a026-5f78af7fc957)

Let me know if it resolve your issue;

**Comment by Hans1205** [comment]
I followed your recommendation today at 1:15 PM but this didn't solve the problem:

![image](https://github.com/fdebrus/hayward-ha/assets/155920388/4b6b4c3d-6f9e-4ab5-a0fa-5fabb996417c)

**Comment by fdebrus** [comment]
That's super weird, can you try once more with 

remove the integration, **restart HA**,  go to HACS, "update information" then "re-download", restart HA, re-install the integration.

If still failing, go to the integration, enable debug logging, restart HA, turn the light of the pool or a relay for the matter on / off (this is just to trigger the integration to perform some stuff). then you can stop debuglogging and send me the output.

!! you might want to remove personal data before posting to web (eg pool_id, node_id, ) just send me the errors if any to start with.

**Comment by Hans1205** [comment]
Hi,

ok, here is what I did:


  *   Delete Aquarite Integration under Setting / Integrations
  *   Restart HA
  *   Under HACS “redownload”
***@***.***

  *   Restart HA
  *   Under Settings / Integrations: add Hayward Aquarite
  *   Enter Username + Password
  *   Select my Pool
***@***.***

  *   This time I additionally created a new area “Pool”
  *   After another Restart HA the Sensors and Controls appear in the Standard Dashboard in the newly created Area “Pool” but also reappear in my customized Dashboard. I think this is expected, because the Names or the sensors and controls are still the same, isn’t it?
  *   A thing I am not sure about is this: is it expected, that the data is still there although I have deleted the integration?
***@***.***

I was looking for a way do really delete old data, but I can’t find a way to achieve this …
  *   After reinstallion the sensors have actual data of course, do I have to wait if this changes …

Regards
Hans

Von: fdebrus ***@***.***>
Gesendet: Freitag, 26. April 2024 09:44
An: fdebrus/hayward-ha ***@***.***>
Cc: Hans1205 ***@***.***>; Author ***@***.***>
Betreff: Re: [fdebrus/hayward-ha] Sensor Data not refreshing (Issue #7)


That's super weird, can you try once more with

remove the integration, restart HA, go to HACS, "update information" then "re-download", restart HA, re-install the integration.

If still failing, go to the integration, enable debug logging, restart HA, turn the light of the pool or a relay for the matter on / off (this is just to trigger the integration to perform some stuff). then you can stop debuglogging and send me the output.

!! you might want to remove personal data before posting to web (eg pool_id, node_id, ) just send me the errors if any to start with.

**Comment by fdebrus** [comment]
If time allow before my flight tomorrow, I will publish a new beta for testing. Some preview of what's coming.
This is not my work, I found this on other github and adapted. It look very nice and will reference the author as this release come out. hopefully, with the new logic it will solve the problem you are having.

![image](https://github.com/fdebrus/hayward-ha/assets/33791533/c762f191-c0ab-48f1-86f1-ee85fbe284f5)

**Comment by Hans1205** [comment]
Hello fdebrus

thank you very much for your hard work and have a nice vacation.

I have now found out something really interesting.
Even after I updated to the integration, I noticed after a short time that the sensor data was not been updated. I thought to myself: maybe there are too many accesses and access is therefore blocked. For example, I have the Vistapool and the DA-Gen app on my cell phone, plus the DA-Gen integration in HA and yours, plus my wife's cell phone ... maybe just too many?!?
So I closed all the apps on my cell phone and also deactivated the DA-gen integration in HA. Unfortunately, no change: still no update of the sensor data.

Then I started the Vistapool app on the cell phone again and the sensor data in the HA was updated immediately. This situation is stable since yesterday lunchtime. I am currently receiving sensor data via your integration in HA.

Is it because I have closed the other integrations and apps or does the integration in HA use the authorization of the app? I don't know, but it might be worth taking a closer look, right? If you want me to provide any log files, please feel free ...

In any case, I have currently achieved exactly what I wanted:

As soon as the PV system's battery is full and there is still electricity coming from the roof, the pool heat pump is switched on, the filtration pump is switched from Smart to Manual and the speed is set to Medium.

If the battery charge level falls below 90%, the heat pump is switched off again, the filtration program is switched back to Smart and the speed to Low.

Perfect! I love it!

And I used your screenshot from dashboard as a template and tried to recreate it. Really cool!

***@***.***

Von: fdebrus ***@***.***>
Gesendet: Freitag, 26. April 2024 21:27
An: fdebrus/hayward-ha ***@***.***>
Cc: Hans1205 ***@***.***>; Author ***@***.***>
Betreff: Re: [fdebrus/hayward-ha] Sensor Data not refreshing (Issue #7)


If time allow before my flight tomorrow, I will publish a new beta for testing. Some preview of what's coming.
This is not my work, I found this on other github and adapted. It look very nice and will reference the author as this release come out. hopefully, with the new logic it will solve the problem you are having.

image.png (view on web)<https://github.com/fdebrus/hayward-ha/assets/33791533/c762f191-c0ab-48f1-86f1-ee85fbe284f5>

**Comment by FRight80** [comment]
I am also experiencing that the sensors stop updating.
Looking though the logs it seems that once the first token expires, the update of the sensors stop. I can still use the switches with the refreshed token, but the data stream through the coordinator stops. If I restart HA, the sensors update again for the first hour, and then stops after the first refresh of the token. I was looking into triggering the subscribe function again when refreshing the token, but was unable to trigger it beyond the first _init_. I don't know if that is the culprit, but was the one I found to be likely.
BTW - I ran the original Dagen installation in parallel, and it is having the same drop, so maybe something changed with the API.

**Comment by fdebrus** [comment]
The token has an expiration time of 1hr, since an update to the API I guess.

hard to tell from something undocumented. 

The .7 and .8 have both a mechanism to refresh the token before expiration. 

I have zero issue with .8 in my setup to date for a week. Which version are you using ? Could you try with the latest beta ?

**Comment by FRight80** [comment]
Thanks, I had the issue in 0.07.
Tested 0.08.b1 which indeed seems to have fixed the issue! Sorry for not checking the beta version before posting. On the positive side it seems I guessed right on the subscribe thing :-)
So far I've seen no issues with 0.08

**Comment by fdebrus** [comment]
solved in 0.08.b1
